# Generated by Django 3.1.4 on 2020-12-23 14:31

from django.db import migrations, models
import sell.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='TITLE')),
                ('brand', models.CharField(max_length=30, verbose_name='BRAND')),
                ('slug', models.SlugField(allow_unicode=True, help_text='one word for title alias', unique=True, verbose_name='SLUG')),
                ('price', models.FloatField(verbose_name='PRICE')),
                ('image', sell.fields.ThumbnailImageField(upload_to='merchandise/%Y/%m')),
                ('description', models.TextField(blank=True, verbose_name='Merchandise Description')),
                ('rating', models.FloatField(verbose_name='RATING')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='CREATE DATE')),
                ('modify_dt', models.DateTimeField(auto_now=True, verbose_name='MODIFY DATE')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
