# Generated by Django 3.1.4 on 2020-12-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_auto_20201223_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='price',
            field=models.FloatField(verbose_name='PRICE'),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='rating',
            field=models.FloatField(verbose_name='RATING'),
        ),
    ]
