# Generated by Django 3.1.4 on 2021-01-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0004_merchandise_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='RATING'),
        ),
    ]
